# Generated by Django 4.2.9 on 2025-10-08 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='expenses.expense'),
        ),
    ]
