# Generated by Django 4.2.9 on 2025-10-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_requires_finance_approval'),
        ('approvals', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'ordering': ['level', '-created_at']},
        ),
        migrations.AddField(
            model_name='approval',
            name='level',
            field=models.IntegerField(choices=[(1, 'Manager Approval'), (2, 'Finance Approval')], default=1, help_text='Approval level in the hierarchy'),
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together={('expense', 'level')},
        ),
    ]
