# Generated by Django 4.2.9 on 2025-10-08 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('segments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Departments that can use this segment. Leave empty for all departments.', related_name='segments', to='users.department'),
        ),
        migrations.AddField(
            model_name='budget',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='users.department'),
        ),
        migrations.AddField(
            model_name='budget',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='segments.segment'),
        ),
    ]
