# Generated by Django 4.2.9 on 2025-10-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='requires_finance_approval',
            field=models.BooleanField(default=False, help_text='If True, expense requires both manager and finance approval'),
        ),
    ]
